### ISSUE TITLE
Python 3: Usage of threading.currentThread

### ISSUE THREAD

**Issue by sebix** [pyload/utils#1]
`pyload/utils/struct/lock.py` has this:
```python
from ..layer.safethreading import Condition, Lock, RLock, currentThread
```
This `pyload/utils/layer/safethreading.py` has:
```python
try:
    from threading import *
except ImportError:
    from dummy_threading import *
```

threading exists, so those names will be imported. But the alias currentThread is not exported, as the actual name is `current_thread`.

As far as I see, both 2.7 and 3.x have current_thread, simply replacing it should be fine.

**Comment by vuolter** [comment]
Thank you for the report! :D

**Comment by sebix** [comment]
Well, thanks for the development ;)

Once you are finished with all my bug report I can test master - probably I find more of them :)
